// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nddfmyzthgecmnxsqtlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZGZteXp0aGdlY21ueHNxdGxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDA3MTksImV4cCI6MjA2NDMxNjcxOX0.pdUHkmAsqkp6Gi7SwVn70ZoH-_k_rWvSrbodHoWNbro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);